### ISSUE TITLE
Scale looks incorrect for determinant plots

### ISSUE THREAD

**Issue by robertconnelly** [robertconnelly/symmetric-tensegrity#16]
The determinant plots allow for the intercepts slider to go off the end. In one tensegrity realization, the change in display does not look to match up with the change in where the determinant plot is.

For example with, A5Z2, cable value [(12354,-(143)], strut alue (15342), there is a crossing point in the determinant graph that changes the tensegrity realization drastically but doesn't look to line up with where the intercept line is.

**Comment by abramconnelly** [comment]
Potentially resolved by #24?

**Comment by robertconnelly** [comment]
y-intercept issue fixed this issue. (#23)
