### ISSUE TITLE
Axies should be labelled in determinant plot

### ISSUE THREAD

**Issue by robertconnelly** [robertconnelly/symmetric-tensegrity#17]
The determinant plot does not have axies visible or labelled. The axies for the determinant plot should be visible and labelled (and look nice).

**Comment by abramconnelly** [comment]
PR #24 partially resolves this by providing axes with tics and numbers. The axes themselves aren't labelled so this issue isn't resolved by #24.

**Comment by robertconnelly** [comment]
OK as is.
