### ISSUE TITLE
Fullscreen mode in Firefox is very jaggy

### ISSUE THREAD

**Issue by robertconnelly** [robertconnelly/symmetric-tensegrity#3]
When enabling fullscreen in Firefox, the tensegrity appears very jaggy, as if it were rendered at a very low resolution even though the picture is fullscreen.

**Comment by robertconnelly** [comment]
I am having trouble with getting my laptop to run the program.  It comes up but there is no picture and the cables and strut windows do not show anything.  I did download the latest Java but that did not do anything.

**Comment by abramconnelly** [comment]
This is not an issue with the fullscreen functionality but is it's own separate issue.  If you could, please create a new issue with details about the issue you're having and keep discussion in any particular issue thread focused on the relevant issue.

**Comment by abramconnelly** [comment]
Pull request #5 should fix this issue.
