### ISSUE TITLE
Laptop not running properly.

### ISSUE THREAD

**Issue by robertconnelly** [robertconnelly/symmetric-tensegrity#6]
See the previous issue with my laptop.

**Comment by abramconnelly** [comment]
Could you give detail on the browser you're running (browser name, version information, etc.) and the operating system you're under?  If you could, could you also open a debug window and see if there are any error messages there?  If so, could you include them in this ticket?

**Comment by robertconnelly** [comment]
Sorry not to do the issues thing properly.  Here is what the page looks like when I run the program:
[Screen Shot 2018-02-20 at 9.45.12 AM-HSTS.pdf](https://github.com/robertconnelly/symmetric-tensegrity/files/1740585/Screen.Shot.2018-02-20.at.9.45.12.AM-HSTS.pdf)
I am going to turn on Java now to see if that works.

**Comment by robertconnelly** [comment]
Ha!  I went to Java, and it said I had to enable it for it to work.  I did that, but it did not run when I tried to use google chrome. So I ran the program with Safari, and everything seemed to work.  So I think it is OK, now.  I'll fuss about getting it to run with google chrome later.  The full screen is nice, with good perspective.  I hope people will like the viewing.  Thanks Abram.

**Comment by abramconnelly** [comment]
Thanks for the screenshot but it's not very helpful.  Could you give me what laptop you're using along with detailed information about what operating system you're running?  Could you give me detailed information about which browser you're running including the version number?

Could you also bring up the 'developer window' (in Chrome, hit `ctrl + shift + j`) and make sure it's in the `console` tab.  If there is any text in **red**, could you paste it here to give more indication about what might be wrong?

I don't know why doing anything with Java would make any sort of difference.  This is JavaScript and there is not Java anywhere in the new code.  Are you trying to run the old code?

**Comment by robertconnelly** [comment]
jre-8u161-macosx-x64 (1).dmg
http://sdlc-esd.oracle.com/ESD6/JSCDL/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jre-8u161-macosx-x64.dmg?GroupName=JSC&FilePath=/ESD6/JSCDL/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jre-8u161-macosx-x64.dmg&BHost=javadl.sun.com&File=jre-8u161-macosx-x64.dmg&AuthParam=1519140308_5358a4db392
Show in Finder 
This is what I see after control shift j in Chrome.
My laptop is a MacBook Air (13-inch, Mid 2011)
Processor 1.7GHz Intel Core 15
Memory 4 GB 1333 MHz DDR3
Graphics 3000 384 MB
 
The browser that worked was Safari version 11.0.3 (11604.5.6.1.1)
Chrome says it is up to date and is version 64.0.3282.167 (Official build) (64-bit)

**Comment by robertconnelly** [comment]
Thanks Abram,

I did what you asked below in the comments page of git hub.

LD

On Feb 20, 2018, at 11:58 AM, Abram Connelly <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the screenshot but it's not very helpful. Could you give me what laptop you're using along with detailed information about what operating system you're running? Could you give me detailed information about which browser you're running including the version number?

Could you also bring up the 'developer window' (in Chrome, hit ctrl + shift + j) and make sure it's in the console tab. If there is any text in red, could you paste it here to give more indication about what might be wrong?

I don't know why doing anything with Java would make any sort of difference. This is JavaScript and there is not Java anywhere in the new code. Are you trying to run the old code?

**Comment by robertconnelly** [comment]
This was taken care nicely.
